/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.word.editor.core;

import java.awt.BorderLayout;
import javafx.application.Platform;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.word.editor.core//WebView//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "WebViewTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
//@ActionID(category = "Window", id = "org.word.editor.core.WebViewTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_WebViewAction",
        preferredID = "WebViewTopComponent"
)
@Messages({
    "CTL_WebViewAction=WebView",
    "CTL_WebViewTopComponent=WebView Window",
    "HINT_WebViewTopComponent=This is a WebView window"
})
public final class WebViewTopComponent extends TopComponent {
    private WebPanel webPanel=new WebPanel();

    public WebViewTopComponent() {
        initComponents();
        setName(Bundle.CTL_WebViewTopComponent());
        setToolTipText(Bundle.HINT_WebViewTopComponent());
        
        setLayout(new BorderLayout());
        add(webPanel.jfxpanel,BorderLayout.CENTER);//将fxpanel添加到页面中间
        Platform.setImplicitExit(false);
    }
    public WebViewTopComponent(String url){
        this();
        webPanel.loadURL(url);
    }
    //设置ｗｅｂ的页面内容
//    public void loadURL(String url){
//        this.webPanel.loadURL(url);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
